services:
  db:
    image: postgis/postgis:15-3.3
    container_name: postgis-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    restart: unless-stopped

  adminer:
      image: adminer
      container_name: adminer-db-ui
      ports:
        - 8080:8080
      depends_on:
        - db
      restart: unless-stopped

volumes:
  postgres_data:
