services:
  app:
    build: .
    container_name: nest-backend
    environment:
      - NODE_ENV=production

      # db настройки
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

      # s3 настройки
      - S3_URL=${S3_URL}
      - S3_REGION=${S3_REGION}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_FORCE_PATH=${S3_FORCE_PATH}

      # настройки проекта
      - HOST=0.0.0.0
      - PORT=${PORT}
      - LOG_LEVEL=${LOG_LEVEL}
      - API_KEY=${API_KEY}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}

      # настройки сайта
      - APP_BASE_URL=${APP_BASE_URL}

      # leader api url и токены
      - LEADER_API_URL=${LEADER_API_URL}
      - LEADER_OAUTH_URL=${LEADER_OAUTH_URL}
      - LEADER_CLIENT_ID=${LEADER_CLIENT_ID}
      - LEADER_CLIENT_SECRET=${LEADER_CLIENT_SECRET}

      # timepad api url и токены
      - TIMEPAD_API_URL=${TIMEPAD_API_URL}
      - TIMEPAD_OAUTH_URL=${TIMEPAD_OAUTH_URL}
      - TIMEPAD_TOKEN=${TIMEPAD_TOKEN}
      - TIMEPAD_CLIENT_ID=${TIMEPAD_CLIENT_ID}

      # настройки почтового модуля
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_SECURE=${MAIL_SECURE}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM=${MAIL_FROM}
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
